import { FaArrowLeft, FaArrowRight } from "react-icons/fa";
import { v4 as uuid } from "uuid";
export const navbarNavigations = [
    {
        id: uuid(),
        icon: FaArrowRight,
        label: "Home",
        slug: "home",
        href: "/",
        hrefMethod: () => router.push("/"),
        active: false,
        show: true,
        children: [],
        place: "top",
    },
    {
        id: uuid(),
        icon: FaArrowRight,
        label: "About",
        slug: "about",
        href: "/about",
        hrefMethod: () => router.push("/about"),
        active: false,
        show: true,
        children: [],
        place: "top",
    },
    {
        id: uuid(),
        icon: FaArrowRight,
        label: "Services",
        slug: "services",
        href: "/services",
        hrefMethod: () => router.push("/services"),
        active: false,
        show: true,
        children: [],
        place: "top",
    },
    {
        id: uuid(),
        icon: FaArrowRight,
        label: "Contact",
        slug: "contact",
        href: "/contact",
        hrefMethod: () => router.push("/contact"),
        active: false,
        show: true,
        children: [],
        place: "top",
    },

    {
        id: uuid(),
        icon: FaArrowRight,
        label: "Dashboard",
        slug: "",
        href: "/dashboard",
        hrefMethod: () => router.push("/dashboard"),
        active: false,
        show: true,
        children: [],
        place: "right",
    },
    {
        id: uuid(),
        icon: FaArrowRight,
        label: "Settings",
        slug: "",
        href: "/settings",
        hrefMethod: () => router.push("/settings"),
        active: false,
        show: true,
        children: [],
        place: "right",
    },
    {
        id: uuid(),
        icon: FaArrowRight,
        label: "Profile",
        slug: "profile",
        href: "/profile",
        hrefMethod: () => router.push(`/auth/register`),
        active: false,
        show: true,
        children: [],
        place: "right",
    },
    {
        id: uuid(),
        icon: FaArrowLeft,
        label: "Sign Out",
        slug: "auth-logout",
        href: "/auth/logout",
        hrefMethod: () => router.push("/auth/logout"),
        active: false,
        show: true,
        children: [],
        method: (e) => handelSignout(e),
        place: "right",
    },
];
